### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Lindseyblocksom** [fodfodfod/learning-github#3]
the bee movie code is very enthralling

**Comment by fodfodfod** [comment]
I think @Lindseyblocksom is very wrong. it was added to the main branch with the pull request #1

**Comment by Lindseyblocksom** [comment]
> I think @Lindseyblocksom is very wrong. it was added to the main branch with the pull request #1

cap

**Comment by fodfodfod** [comment]
I think we solved this problem so I am going to close this issue
